apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  name: jx-scheduler
spec:
  lgtm:
    reviewActsAsLgtm: true
  merger:
    mergeMethod: rebase
  plugins:
    entries:
      - label
  postsubmits:
    replace: true
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      name: release
      context: ""
      policy:
        requiredStatusChecks:
          contexts:
            entries:
            # - whitesource
    # - agent: tekton
    #   branches:
    #     entries:
    #     - master
    #   cluster: ""
    #   context: whitesource
    #   labels: {}
    #   maxConcurrency: 0
    #   name: whitesource
    #   report: false
    #   runIfChanged: ""
    #   skipBranches: {}
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: true
      context: e2e
      name: e2e
      policy:
        requiredStatusChecks:
          contexts:
            entries:
              - fmt
              - clippy
              - unit
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test e2e
      trigger: (?m)^/test( all| e2e),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      context: fmt
      name: fmt
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test fmt
      trigger: (?m)^/test( all| fmt),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      context: clippy
      name: clippy
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test clippy
      trigger: (?m)^/test( all| clippy),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      context: unit
      name: unit
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test unit
      trigger: (?m)^/test( all| unit),?(\s+|$)

