apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jx
  name: jx-admin
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jx-staging
  name: jx-admin
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jx-production
  name: jx-admin
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
