apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-bucketrepo
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-controllerbuild
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-controllerrole
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-gcactivities
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-gcpods
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-gcpreviews
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-heapster
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-lighthouse
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tide
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-bot
  namespace: jx

