{{- if eq .Requirements.webhook "prow" }}
enabled: true
{{- else if eq .Requirements.webhook "lighthouse" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

webhook:
  enabled: false

auth:
  git:
    username: "{{ .Parameters.pipelineUser.username }}"
    password: "{{ .Parameters.pipelineUser.token }}"
    url: {{ .Requirements.cluster.gitServer | default "https://github.com" }}
{{- if hasKey .Parameters "docker" }}
  docker:
    username: "{{ .Parameters.docker.username }}"
    password: "{{ .Parameters.docker.password }}"
    url: "{{ .Parameters.docker.url }}"
{{- end }}

tillerNamespace: ""

{{- if hasKey .Requirements.cluster "strictPermissions" }}
{{- if and (eq .Requirements.cluster.provider "openshift") (.Requirements.cluster.strictPermissions) }}
rbac:
  cluster: false
cluster:
  crds:
    create: false
  resources:
    create: false
{{- end }}
{{- end }}
